# Generated by Django 2.2.9 on 2019-12-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='類別名稱')),
            ],
            options={
                'verbose_name': '餐廳類別',
                'verbose_name_plural': '餐廳類別',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='稱呼')),
                ('email', models.EmailField(max_length=254, verbose_name='信箱')),
                ('category', models.CharField(max_length=10, verbose_name='類型')),
                ('comment', models.TextField(verbose_name='建議內容')),
                ('handle', models.BooleanField(default=False, verbose_name='是否已處理')),
            ],
            options={
                'verbose_name': '建議',
                'verbose_name_plural': '建議',
                'db_table': 'suggestion',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='餐廳名稱')),
                ('address', models.TextField(max_length=255, verbose_name='餐廳位置')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='餐廳電話')),
                ('time', models.CharField(max_length=50, verbose_name='營業時間')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='介紹')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.Category')),
            ],
            options={
                'verbose_name': '餐廳',
                'verbose_name_plural': '餐廳',
                'db_table': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='CommentField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='稱呼')),
                ('grade', models.SmallIntegerField(verbose_name='評分')),
                ('comment', models.TextField(verbose_name='評論')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.Restaurant')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'db_table': 'comments',
            },
        ),
    ]
